dist: bionic
language: julia
julia:
  - 1.6.2
script:
  - julia -e 'using Pkg; Pkg.test(;coverage=true)'
  - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile();'
  - julia --project=. -e 'using Pkg; Pkg.add(["FileIO", "JLD2", "CodecZlib"])'
  - julia --project=. benchmark/benchmark.jl
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; bytes = getproperty.(Coverage.analyze_malloc("."), :bytes) |> sum; exit(ifelse(bytes==0, 0, 1))'

after_success:
- julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
- julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
