dist: bionic
language: julia
julia:
  - 1.6.2
script:
  - julia -e 'using Pkg; Pkg.test(;coverage=true)'
  - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile();'
  - julia --project=. -e 'using Pkg; Pkg.add(["FileIO", "JLD2", "CodecZlib"])'
  - julia --project=. benchmark/benchmark.jl

after_success:
- julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
